{
 "title": "Herovire App",
 "tags": [
  "herovire",
  "capstone"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pods up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{job=\"herovire-app\"})",
     "legendFormat": "up"
    }
   ]
  },
  {
   "title": "Requests / sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m]))",
     "legendFormat": "all requests"
    }
   ]
  },
  {
   "title": "Request rate by status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(flask_http_request_total[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}