apiVersion: apps/v1
kind: Deployment
metadata:
  name: herovire-app
  labels:
    app: herovire-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: herovire-app
  template:
    metadata:
      labels:
        app: herovire-app
    spec:
      containers:
        - name: herovire-app
          image: 859666866036.dkr.ecr.ap-south-1.amazonaws.com/herovire-app:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
